"""
admin_data_generator.py – Script sinh dữ liệu test cho NOAH Retail

Chức năng:
  --mode csv     : Sinh inventory.csv (với ~5% dữ liệu bẩn)
  --mode orders  : Sinh dữ liệu đơn hàng mẫu
  --mode both    : Sinh cả hai

Sử dụng:
  python admin_data_generator.py --mode csv
  python admin_data_generator.py --mode orders
  python admin_data_generator.py --mode both --count 100
"""

import os
import csv
import random
import argparse
from datetime import datetime

# ─── Các sản phẩm hợp lệ (product_id 100-299) ────────────────────
VALID_IDS = list(range(100, 300))


def generate_inventory_csv(output_dir: str = "input", count: int = 200, dirty_pct: float = 0.05):
    """
    Sinh file inventory.csv vào thư mục output_dir.
    Khoảng dirty_pct % dòng sẽ là dữ liệu bẩn:
      - quantity âm
      - product_id = 0 hoặc âm
      - thiếu field
      - ký tự không hợp lệ
    """
    os.makedirs(output_dir, exist_ok=True)
    filepath = os.path.join(output_dir, "inventory.csv")

    num_dirty  = max(1, int(count * dirty_pct))
    num_clean  = count - num_dirty
    dirty_rows = random.sample(range(count), num_dirty)

    rows = []
    for i in range(count):
        if i in dirty_rows:
            error_type = random.choice(["negative_qty", "zero_id", "missing_field", "invalid_char"])
            if error_type == "negative_qty":
                rows.append({"product_id": str(random.choice(VALID_IDS)), "quantity": str(random.randint(-50, -1))})
            elif error_type == "zero_id":
                rows.append({"product_id": "0", "quantity": str(random.randint(1, 100))})
            elif error_type == "missing_field":
                rows.append({"product_id": str(random.choice(VALID_IDS)), "quantity": ""})
            else:
                rows.append({"product_id": "ABC!@#", "quantity": "XYZ"})
        else:
            rows.append({
                "product_id": str(random.choice(VALID_IDS)),
                "quantity":   str(random.randint(1, 200))
            })

    # Shuffle để dirty rows rải rác
    random.shuffle(rows)

    with open(filepath, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=["product_id", "quantity"])
        writer.writeheader()
        writer.writerows(rows)

    print(f"✔ CSV đã tạo: {filepath}")
    print(f"  Tổng số dòng  : {count}")
    print(f"  Dữ liệu hợp lệ: {num_clean}")
    print(f"  Dữ liệu bẩn  : {num_dirty} (~{dirty_pct*100:.0f}%)")


def generate_orders_sql(output_dir: str = "admin_output", count: int = 50):
    """
    Sinh SQL INSERT mẫu cho bảng orders.
    """
    os.makedirs(output_dir, exist_ok=True)
    filepath = os.path.join(output_dir, "sample_orders.sql")

    lines = ["-- Sample orders generated by admin_data_generator.py\n"]
    lines.append("USE noah_store;\n")
    lines.append("INSERT INTO orders (user_id, product_id, quantity, total_price, status, created_at) VALUES\n")

    rows = []
    for i in range(count):
        user_id    = random.randint(1, 1000)
        product_id = random.choice(VALID_IDS)
        quantity   = random.randint(1, 5)
        price      = random.randint(100000, 5000000)
        total      = price * quantity
        status     = random.choice(["PENDING", "COMPLETED"])
        created_at = f"2026-{random.randint(1,2):02d}-{random.randint(1,28):02d} {random.randint(0,23):02d}:{random.randint(0,59):02d}:00"
        rows.append(f"  ({user_id}, {product_id}, {quantity}, {total}, '{status}', '{created_at}')")

    lines.append(",\n".join(rows) + ";\n")

    with open(filepath, "w", encoding="utf-8") as f:
        f.writelines(lines)

    print(f"✔ SQL orders đã tạo: {filepath} ({count} đơn hàng)")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="NOAH Retail Data Generator")
    parser.add_argument("--mode", choices=["csv", "orders", "both"], default="csv",
                        help="Chế độ sinh dữ liệu")
    parser.add_argument("--count", type=int, default=200,
                        help="Số lượng dòng/đơn hàng cần sinh")
    parser.add_argument("--dirty", type=float, default=0.05,
                        help="Tỷ lệ dữ liệu bẩn (0.0 - 1.0)")
    parser.add_argument("--outdir", type=str, default="input",
                        help="Thư mục output cho CSV")
    args = parser.parse_args()

    print("=" * 50)
    print(" NOAH RETAIL – Admin Data Generator")
    print(f" Mode : {args.mode}")
    print(f" Count: {args.count}")
    print("=" * 50)

    if args.mode in ("csv", "both"):
        generate_inventory_csv(args.outdir, args.count, args.dirty)

    if args.mode in ("orders", "both"):
        generate_orders_sql(count=args.count)

    print("\nXong! Kiểm tra thư mục output.")
